name: multivender_ecommerce_app
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
##UI
  cupertino_icons:
  flutter_screenutil: "^5.0.0+2"
  outline_gradient_button: ^2.0.0+1
  ##State Management
  provider:
##Futures Reflections
  flutter_spinkit:
  flushbar:
##Firebase
  firebase_core:
  firebase_auth:
  cloud_firestore:
  firebase_storage:
##localImagePicker
  path_provider: ^1.6.27
  image_picker: ^0.6.6+5
##Maps
#  map_pin_picker: ^0.0.1
#  google_maps_flutter: ^1.1.1
  geolocator: ^6.1.14
  geocoder: ^0.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - images/
    - lang/

  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Black.ttf
        - asset: fonts/Roboto-Bold.ttf
        - asset: fonts/Roboto-Regular.ttf
        - asset: fonts/Roboto-Light.ttf

    - family: Rochester
      fonts:
        - asset: fonts/Rochester-Regular.ttf

